spring:
  application.name: order-processor
  main:
    web-application-type: servlet
  profiles.active: ${ENVIRONMENT:local}
  threads:
    virtual.enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    org.jooq.Constants: WARN
    org.javamoney.moneta: WARN
    com.gruelbox.transactionoutbox.TransactionOutboxImpl: WARN

app:
  order:
    event:
      sqs:
        queue-name: ${SQS_QUEUE_ORDER_UPDATED}
    temporary-batch:
      size: ${app.order.orchestrator.chunk-size}
    batch:
      size: ${app.order.orchestrator.chunk-size}
    orchestrator:
      chunk-size: 500
    update:
      s3:
        bucket-name: ${S3_BUCKET_ORDER_UPDATES}
  transaction-outbox:
    resumer-delay: PT5M
    flush-batch-size: 2048
    attempt-frequency: PT5M