spring:
  application.name: order-processor
  main:
    web-application-type: servlet
  profiles:
    active: prod
  threads:
    virtual.enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order-processor
    username: username
    password: password
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  shutdown: graceful

app:
  transaction-outbox:
    resumer-delay: PT5M
    flush-batch-size: 2048
    attempt-frequency: PT5M