spring:
  application.name: order-processor
  main:
    web-application-type: servlet
  profiles:
    active: prod
  threads:
    virtual.enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/order-processor
    username: username
    password: password
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.xml
  mvc:
    problemdetails:
      enabled: true

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    org.jooq.Constants: WARN
    org.javamoney.moneta: WARN
    com.gruelbox.transactionoutbox.TransactionOutboxImpl: WARN

app:
  order:
    event:
      sqs:
        queue-name: order-updated-events
    temporary-batch:
      size: ${app.order.orchestrator.chunk-size}
    batch:
      size: ${app.order.orchestrator.chunk-size}
    orchestrator:
      chunk-size: 500
    update:
      s3:
        bucket-name: order-updates
  transaction-outbox:
    resumer-delay: PT5M
    flush-batch-size: 2048
    attempt-frequency: PT5M