spring:
  application.name: batch-processor-tests
  datasource:
    url: "jdbc:tc:postgresql:16-alpine:///batch-processor?TC_REUSABLE=true"
    hikari:
      minimum-idle: 2
      maximum-pool-size: 2
  liquibase:
    enabled: true
    contexts: integration
  cloud:
    aws:
      region:
        static: us-east-1

management:
  metrics:
    enable:
      tomcat: false
      jvm: false
      process: false
      hikaricp: false
      system: false
      jdbc: false
      http: false
      logback: false

logging:
  level:
    io.kraluk.batchprocessor: DEBUG
    org.jooq.Constants: WARN
    org.jooq.tools.LoggerListener: INFO # DEBUG for SQL logs
    com.gruelbox.transactionoutbox.TransactionOutboxImpl: INFO

app:
  transaction-outbox:
    resumer-delay: PT1000H